### ISSUE TITLE
uim 9a37a41 on 9 Jun cannot build on Qt 5.5.1

### ISSUE THREAD

**Issue by dai-vdr** [uim/uim#66]
uim 9a37a41 on 9 Jun (latest 2015/10/24) cannot build on Qt 5.5.1.

```
g++ -c -m64 -pipe -O2 -g -O2 -pipe -W -Wall -Wchar-subscripts -Wnon-virtual-dtor -Wno-long-long -Wcast-align -Wpointer-arith -Wwrite-strings -Wformat-security -DNDEBUG -fvisibility=hidden -fvisibility-inlines-hidden -std=c++0x -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_PLUGIN -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -I/tmp/uim -I/tmp/uim/uim -I/tmp/uim -I/tmp/uim/uim -I/tmp/uim/replace -I../../qt4/candwin -I../../qt4/immodule -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui/5.5.1 -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui/5.5.1/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -o plugin.o ../../qt4/immodule/plugin.cpp
In file included from /usr/include/x86_64-linux-gnu/qt5/QtGui/qregion.h:42:0,
                 from /usr/include/x86_64-linux-gnu/qt5/QtGui/qevent.h:39,
                 from /usr/include/x86_64-linux-gnu/qt5/QtGui/QInputMethodEvent:1,
                 from ./quimplatforminputcontext.h:37,
                 from ../../qt4/immodule/quiminputcontext_with_slave.h:41,
                 from ../../qt4/immodule/plugin.cpp:66:
/usr/include/x86_64-linux-gnu/qt5/QtCore/qdatastream.h:42:2: error: #error qdatastream.h must be included before any header file that defines Status
 #error qdatastream.h must be included before any header file that defines Statu
  ^
```

i moved include quiminputcontext_with_slave.h upto qpa/qplatforminputcontext.h,
built successfully, but Qt5 immodule could not run on Qt5 application: guarddog, tea.
btw, uim Qt5 immodule built at Qt5.4.2 can run on them.

```diff
diff --git a/qt4/immodule/plugin.cpp b/qt4/immodule/plugin.cpp
index d711b7c..7942e6a 100644
--- a/qt4/immodule/plugin.cpp
+++ b/qt4/immodule/plugin.cpp
@@ -43,6 +43,7 @@
 #if QT_VERSION < 0x050000
 # include <QtGui/QInputContext>
 #else
+# include "quiminputcontext_with_slave.h"
 # include <qpa/qplatforminputcontext.h>
 #endif
 
@@ -63,7 +64,9 @@
 # undef KeyRelease
 # undef None
 #endif
+#if QT_VERSION < 0x050000
 #include "quiminputcontext_with_slave.h"
+#endif
 
 #define UIM_QT_LIST_SUBIM_AS_QTIM 0
 ```

**Comment by dai-vdr** [comment]
related NgoHuy/uim@f0948b38c67f7b209e7718fd445cccf9287b7887

**Comment by dai-vdr** [comment]
related TheSLinux-forks/uim#5

**Comment by dai-vdr** [comment]
this issue is fixed by TheSLinux-forks/uim#5 and TheSLinux-forks/uim#6

**Comment by dai-vdr** [comment]
9c00808
04f8f9c9

**Comment by dai-vdr** [comment]
all merged.
